/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Product;
import Service.ProductService;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author jaywalker
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() throws Exception {
        initComponents();      
        this.openProductFrame();
        this.loadDataOnList(new ProductService());
        this.getSelectedItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstProducts = new javax.swing.JList<>();
        btnCreateProduct = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstProducts.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstProducts);

        btnCreateProduct.setText("Add Product");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateProduct)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreateProduct)
                .addGap(75, 75, 75)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void openProductFrame() {
        this.btnCreateProduct.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {         
                ProductFrame pf = new ProductFrame(MainFrame.this);
                pf.setVisible(true);
            }
        });
    }
    
    public void loadDataOnList(ProductService productService) throws Exception {
        DefaultListModel listModel = new DefaultListModel();
        ArrayList<Product> products = new ArrayList<Product>();
        products = productService.list();
        for (Product p : products) {
            listModel.addElement(p);
        }
        lstProducts.setModel(listModel);
    }
    
    public void getSelectedItem() {      
//        lstProducts.addMouseListener(new MouseAdapter() {
//            @Override 
//            public void mouseClicked(MouseEvent e) {
//                
////                Product p = (Product) lstProducts.getSelectedValue();
//                System.out.println("clicked: " + lstProducts.getSelectedValue());
//            }
//        });
        lstProducts.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent arg0) {
                if (!arg0.getValueIsAdjusting()) {
                    try {
                        int index = lstProducts.getSelectedIndex();
                        System.out.println(lstProducts.getModel().getElementAt(index));
                    } catch(Exception e) {
                        System.out.println("blla");
                    }
//                    String p = String.valueOf(lstProducts.getModel().getElementAt(arg0.getLastIndex()));
//                    System.out.println(p);
//                  System.out.println(lstProducts.getSelectedValue().toString());
                }
//                String p = lstProducts.getModel().getElementAt(arg0.getLastIndex());
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateProduct;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstProducts;
    // End of variables declaration//GEN-END:variables
}
